server {
    listen 80;
    server_name localhost;  # add your domain name or IP address if needed
    
    # static landing page
    root /usr/share/nginx/html;
    index index.html;

    # Reverse proxy for Icecast (endpoint /stream)
    location /stream/ {
        proxy_pass http://icecast:8000/stream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Reverse proxy for status in JSON (if you want to display "Now Playing" information)
    location /status-json.xsl {
        proxy_pass http://icecast:8000/status-json.xsl;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
